-- Accession Register / OPAC - Version 1
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.ddc_master (
  id bigint generated by default as identity primary key,
  ddc_number text not null unique,
  subject text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.location_master (
  id bigint generated by default as identity primary key,
  location_code text not null unique,
  location_name text not null,
  shelf text,
  created_at timestamptz not null default now()
);

create table if not exists public.accessions (
  id uuid primary key default gen_random_uuid(),
  accession_no text not null unique,
  accession_date date not null default current_date,
  title text not null,
  subtitle text,
  edition text,
  publisher text,
  publication_place text,
  publication_year integer,
  isbn text,
  pages text,
  price numeric(12,2),
  ddc_number text,
  subject text,
  location_id bigint references public.location_master(id) on delete set null,
  language text,
  book_type text,
  remarks text,
  source text check (source is null or source in ('State Central Library','RRRLF','Donation/Gift')),
  rrrlf_scheme text,
  status text not null default 'Available'
    check (status in ('Available','Issued','Lost','Withdrawn','Damaged')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint accessions_rrrlf_scheme_check check (
    (source = 'RRRLF' and rrrlf_scheme in (
      'Donated/Gifted by RRRLF',
      'Purchased with Assistance from RRRLF',
      'Matching Scheme'
    ))
    or
    (source is distinct from 'RRRLF' and rrrlf_scheme is null)
  )
);

create table if not exists public.accession_authors (
  id bigint generated by default as identity primary key,
  accession_id uuid not null references public.accessions(id) on delete cascade,
  author_order smallint not null check (author_order between 1 and 3),
  author_name text not null,
  unique(accession_id, author_order)
);

create table if not exists public.accession_contributors (
  id bigint generated by default as identity primary key,
  accession_id uuid not null references public.accessions(id) on delete cascade,
  contributor_name text not null,
  contributor_role text,
  unique(accession_id, contributor_name, contributor_role)
);

create index if not exists idx_accessions_title on public.accessions using gin (to_tsvector('simple', title));
create index if not exists idx_accessions_isbn on public.accessions(isbn);
create index if not exists idx_accessions_ddc on public.accessions(ddc_number);
create index if not exists idx_accessions_source on public.accessions(source);
create index if not exists idx_accessions_rrrlf_scheme on public.accessions(rrrlf_scheme);
create index if not exists idx_authors_name on public.accession_authors(author_name);

-- Public OPAC reads.
alter table public.accessions enable row level security;
alter table public.accession_authors enable row level security;
alter table public.accession_contributors enable row level security;
alter table public.ddc_master enable row level security;
alter table public.location_master enable row level security;

drop policy if exists "OPAC can read accessions" on public.accessions;
create policy "OPAC can read accessions"
on public.accessions for select to anon, authenticated using (true);

drop policy if exists "OPAC can read authors" on public.accession_authors;
create policy "OPAC can read authors"
on public.accession_authors for select to anon, authenticated using (true);

drop policy if exists "OPAC can read contributors" on public.accession_contributors;
create policy "OPAC can read contributors"
on public.accession_contributors for select to anon, authenticated using (true);

drop policy if exists "OPAC can read ddc" on public.ddc_master;
create policy "OPAC can read ddc"
on public.ddc_master for select to anon, authenticated using (true);

drop policy if exists "OPAC can read locations" on public.location_master;
create policy "OPAC can read locations"
on public.location_master for select to anon, authenticated using (true);

-- The server secret key is never placed in the browser.
-- Server-side writes can use the secret key after authentication/authorization.
