import express from "express";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { supabasePublic, supabaseAdmin } from "./supabase.js";

const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),app=express(),PORT=Number(process.env.PORT||3000);
const ADMIN_USERNAME=process.env.ADMIN_USERNAME||"",ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"",SESSION_SECRET=process.env.SESSION_SECRET||"",COOKIE_NAME="sdlm_staff_session",SESSION_MAX_AGE=8*60*60;
app.use(express.json({limit:"1mb"}));
function sign(v){return crypto.createHmac("sha256",SESSION_SECRET).update(v).digest("hex")}
function makeSession(u){const p=Buffer.from(JSON.stringify({u,exp:Math.floor(Date.now()/1000)+SESSION_MAX_AGE})).toString("base64url");return `${p}.${sign(p)}`}
function readSession(req){if(!SESSION_SECRET)return null;const f=(req.headers.cookie||"").split(";").map(x=>x.trim()).find(x=>x.startsWith(`${COOKIE_NAME}=`));if(!f)return null;const t=decodeURIComponent(f.slice(COOKIE_NAME.length+1)),d=t.lastIndexOf(".");if(d<1)return null;const p=t.slice(0,d),s=t.slice(d+1),e=sign(p);if(s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return null;try{const x=JSON.parse(Buffer.from(p,"base64url").toString("utf8"));return x.u&&x.exp>=Math.floor(Date.now()/1000)?x:null}catch{return null}}
function requireStaff(req,res,next){if(!ADMIN_USERNAME||!ADMIN_PASSWORD||!SESSION_SECRET)return res.status(503).json({error:"Staff login is not configured."});const s=readSession(req);if(!s)return res.status(401).json({error:"Staff authentication required."});req.staff=s;next()}
const accessionSelect=`*, location_master(location_code,location_name,shelf), accession_authors(author_order,author_name), accession_contributors(contributor_name,contributor_role)`;
app.get("/api/health",async(_q,r)=>{const{error}=await supabasePublic.from("ddc_master").select("id").limit(1);r.json({ok:!error,database:error?"error":"connected"})});
app.post("/api/auth/login",(q,r)=>{const u=String(q.body?.username||""),p=String(q.body?.password||"");if(!ADMIN_USERNAME||!ADMIN_PASSWORD||!SESSION_SECRET)return r.status(503).json({error:"Staff login is not configured."});if(u!==ADMIN_USERNAME||p!==ADMIN_PASSWORD)return r.status(401).json({error:"Invalid username or password."});r.setHeader("Set-Cookie",`${COOKIE_NAME}=${encodeURIComponent(makeSession(u))}; Max-Age=${SESSION_MAX_AGE}; Path=/; HttpOnly; SameSite=Lax; Secure`);r.json({ok:true})});
for(const route of ["/api/auth/logout","/api/logout"])app.post(route,(_q,r)=>{r.setHeader("Set-Cookie",`${COOKIE_NAME}=; Max-Age=0; Path=/; HttpOnly; SameSite=Lax; Secure`);r.json({ok:true})});
app.get("/api/auth/me",(q,r)=>{const s=readSession(q);if(!s)return r.status(401).json({authenticated:false});r.json({authenticated:true,username:s.u})});
app.get("/api/ddc",async(q,r)=>{const x=String(q.query.q||"").trim();let z=supabasePublic.from("ddc_master").select("id,ddc_number,subject").order("ddc_number").limit(50);if(x)z=z.or(`ddc_number.ilike.%${x}%,subject.ilike.%${x}%`);const{data,error}=await z;if(error)return r.status(500).json({error:error.message});r.json(data||[])});
app.get("/api/locations",async(_q,r)=>{const{data,error}=await supabasePublic.from("location_master").select("id,location_code,location_name,shelf").order("location_name");if(error)return r.status(500).json({error:error.message});r.json(data||[])});
app.get("/api/opac/search",async(q,r)=>{const x=String(q.query.q||"").trim();if(!x)return r.json([]);const p=`%${x}%`;const{data,error}=await supabasePublic.from("accessions").select(accessionSelect).or(`title.ilike.${p},isbn.ilike.${p},ddc_number.ilike.${p},subject.ilike.${p},accession_no.ilike.${p}`).order("title").limit(50);if(error)return r.status(500).json({error:error.message});const{data:a}=await supabasePublic.from("accession_authors").select("accession_id").ilike("author_name",p).limit(50);const ids=[...new Set((a||[]).map(v=>v.accession_id))],rows=data||[];if(ids.length){const{data:m}=await supabasePublic.from("accessions").select(accessionSelect).in("id",ids);for(const v of m||[])if(!rows.some(z=>z.id===v.id))rows.push(v)}r.json(rows)});
app.get("/api/accessions/:accessionNo",async(q,r)=>{const{data,error}=await supabasePublic.from("accessions").select(accessionSelect).eq("accession_no",q.params.accessionNo).maybeSingle();if(error)return r.status(500).json({error:error.message});if(!data)return r.status(404).json({error:"Accession not found."});r.json(data)});
app.get("/api/accessions/search",requireStaff,async(q,r)=>{const x=String(q.query.q||"").trim(),p=`%${x}%`;let z=supabaseAdmin.from("accessions").select(accessionSelect).order("accession_no").limit(200);if(x)z=z.or(`accession_no.ilike.${p},title.ilike.${p},isbn.ilike.${p},ddc_number.ilike.${p},subject.ilike.${p}`);const{data,error}=await z;if(error)return r.status(500).json({error:error.message});let rows=data||[];if(x){const{data:a}=await supabaseAdmin.from("accession_authors").select("accession_id").ilike("author_name",p).limit(200);const ids=[...new Set((a||[]).map(v=>v.accession_id))];if(ids.length){const{data:m}=await supabaseAdmin.from("accessions").select(accessionSelect).in("id",ids);for(const v of m||[])if(!rows.some(z=>z.id===v.id))rows.push(v)}}r.json(rows)});
app.get("/api/admin/accessions",requireStaff,async(q,r)=>{q.query.q=q.query.q||"";return app._router.handle(q,r,()=>{},"/api/accessions/search")});
app.get("/api/admin/next-accession",requireStaff,async(_q,r)=>{const{data,error}=await supabaseAdmin.from("accessions").select("accession_no").limit(5000);if(error)return r.status(500).json({error:error.message});let max=0;for(const v of data||[]){const x=String(v.accession_no||"");if(/^\d+$/.test(x))max=Math.max(max,+x)}r.json({accession_no:String(max+1)})});
app.post("/api/accessions",requireStaff,async(q,r)=>{const b=q.body||{};if(!b.accession_no||!b.title)return r.status(400).json({error:"accession_no and title are required."});const authors=(Array.isArray(b.authors)?b.authors:[]).slice(0,3).map((x,i)=>({author_order:i+1,author_name:String(x.author_name||x.name||x).trim()})).filter(x=>x.author_name);const{data:a,error}=await supabaseAdmin.from("accessions").insert({accession_no:b.accession_no,accession_date:b.accession_date||undefined,title:b.title,subtitle:b.subtitle||null,edition:b.edition||null,publisher:b.publisher||null,publication_place:b.publication_place||null,publication_year:b.publication_year||null,isbn:b.isbn||null,pages:b.pages||null,price:b.price||null,ddc_number:b.ddc_number||null,subject:b.subject||null,location_id:b.location_id||null,language:b.language||null,book_type:b.book_type||null,remarks:b.remarks||null,status:b.status||"Available"}).select().single();if(error)return r.status(400).json({error:error.message});if(authors.length){const{error:e}=await supabaseAdmin.from("accession_authors").insert(authors.map(x=>({accession_id:a.id,...x})));if(e)return r.status(400).json({error:e.message})}r.status(201).json(a)});
app.get("/api/accessions/id/:id",requireStaff,async(q,r)=>{const{data,error}=await supabaseAdmin.from("accessions").select(accessionSelect).eq("id",q.params.id).maybeSingle();if(error)return r.status(500).json({error:error.message});if(!data)return r.status(404).json({error:"Accession not found."});r.json(data)});
app.put("/api/accessions/id/:id",requireStaff,async(q,r)=>{const b=q.body||{};if(!b.title)return r.status(400).json({error:"Title is required."});const{data,error}=await supabaseAdmin.from("accessions").update({accession_date:b.accession_date||null,title:b.title,subtitle:b.subtitle||null,edition:b.edition||null,publisher:b.publisher||null,publication_place:b.publication_place||null,publication_year:b.publication_year||null,isbn:b.isbn||null,pages:b.pages||null,price:b.price||null,ddc_number:b.ddc_number||null,subject:b.subject||null,location_id:b.location_id||null,language:b.language||null,book_type:b.book_type||null,remarks:b.remarks||null,status:b.status||"Available",updated_at:new Date().toISOString()}).eq("id",q.params.id).select().single();if(error)return r.status(400).json({error:error.message});await supabaseAdmin.from("accession_authors").delete().eq("accession_id",q.params.id);const authors=(Array.isArray(b.authors)?b.authors:[]).slice(0,3).map((x,i)=>({accession_id:q.params.id,author_order:i+1,author_name:String(x.author_name||x.name||x).trim()})).filter(x=>x.author_name);if(authors.length){const{error:e}=await supabaseAdmin.from("accession_authors").insert(authors);if(e)return r.status(400).json({error:e.message})}await supabaseAdmin.from("accession_contributors").delete().eq("accession_id",q.params.id);const cs=(Array.isArray(b.contributors)?b.contributors:[]).map(x=>({accession_id:q.params.id,contributor_name:String(x.contributor_name||x.name||"").trim(),contributor_role:x.contributor_role||x.role||null})).filter(x=>x.contributor_name);if(cs.length){const{error:e}=await supabaseAdmin.from("accession_contributors").insert(cs);if(e)return r.status(400).json({error:e.message})}r.json(data)});
app.delete("/api/accessions/id/:id",requireStaff,async(q,r)=>{const{error}=await supabaseAdmin.from("accessions").delete().eq("id",q.params.id);if(error)return r.status(400).json({error:error.message});r.json({ok:true})});
app.get("/manage",requireStaff,(_q,r)=>r.sendFile(path.join(__dirname,"..","public","manage.html")));
app.get("/admin",(_q,r)=>r.sendFile(path.join(__dirname,"..","public","login.html")));
app.get("/admin.html",(_q,r)=>r.sendFile(path.join(__dirname,"..","public","login.html")));
app.get("/admin-dashboard.html",requireStaff,(_q,r)=>r.sendFile(path.join(__dirname,"..","public","admin.html")));
app.use(express.static(path.join(__dirname,"..","public")));
app.get(/.*/,_q=>{});
app.listen(PORT,"0.0.0.0",()=>console.log(`Accession Register V1 listening on port ${PORT}`));
