-- Overall Accession Register application foundation.
alter table public.location_master add column if not exists section_name text;
alter table public.location_master add column if not exists rack_name text;
create index if not exists idx_location_section_rack_shelf on public.location_master(section_name,rack_name,shelf);
alter table public.ddc_master add column if not exists division_number text;
alter table public.ddc_master add column if not exists section_number text;
create index if not exists idx_ddc_division on public.ddc_master(division_number);
create index if not exists idx_ddc_section on public.ddc_master(section_number);

create table if not exists public.ddc_divisions(id bigint generated by default as identity primary key,division_number text not null unique,name text not null,created_at timestamptz not null default now());
insert into public.ddc_divisions(division_number,name) values
('000','Computer science, information & general works'),('010','Bibliography'),('020','Library & information sciences'),('030','Encyclopedias & books of facts'),('040','[Unassigned]'),('050','Magazines, journals & serials'),('060','Associations, organizations & museums'),('070','News media, journalism & publishing'),('080','Quotations'),('090','Manuscripts & rare books'),
('100','Philosophy & psychology'),('110','Metaphysics'),('120','Epistemology'),('130','Parapsychology & occultism'),('140','Philosophical schools of thought'),('150','Psychology'),('160','Logic'),('170','Ethics'),('180','Ancient, medieval & Eastern philosophy'),('190','Modern Western philosophy'),
('200','Religion'),('210','Philosophy & theory of religion'),('220','Bible'),('230','Christianity & Christian theology'),('240','Christian practice & observance'),('250','Christian orders & local church'),('260','Christianity & social/ecclesiastical theology'),('270','History of Christianity'),('280','Christian denominations'),('290','Other religions'),
('300','Social sciences'),('310','Statistics'),('320','Political science'),('330','Economics'),('340','Law'),('350','Public administration & military science'),('360','Social problems & social services'),('370','Education'),('380','Commerce, communications & transportation'),('390','Customs, etiquette & folklore'),
('400','Language'),('410','Linguistics'),('420','English & Old English'),('430','German & related languages'),('440','French & related Romance languages'),('450','Italian, Romanian & related languages'),('460','Spanish & Portuguese languages'),('470','Latin & Italic languages'),('480','Classical & modern Greek languages'),('490','Other languages'),
('500','Science'),('510','Mathematics'),('520','Astronomy'),('530','Physics'),('540','Chemistry'),('550','Earth sciences & geology'),('560','Paleontology'),('570','Life sciences & biology'),('580','Plants / botany'),('590','Animals / zoology'),
('600','Technology'),('610','Medicine & health'),('620','Engineering'),('630','Agriculture'),('640','Home & family management'),('650','Management & auxiliary services'),('660','Chemical engineering'),('670','Manufacturing'),('680','Manufacture for specific uses'),('690','Buildings'),
('700','Arts & recreation'),('710','Area planning & landscape architecture'),('720','Architecture'),('730','Sculpture, ceramics & metalwork'),('740','Drawing & decorative arts'),('750','Painting'),('760','Printmaking & prints'),('770','Photography & computer art'),('780','Music'),('790','Recreational & performing arts'),
('800','Literature'),('810','American literature in English'),('820','English & Old English literatures'),('830','German & related literatures'),('840','French & related literatures'),('850','Italian, Romanian & related literatures'),('860','Spanish & Portuguese literatures'),('870','Latin & Italic literatures'),('880','Classical & modern Greek literatures'),('890','Literatures of other languages'),
('900','History & geography'),('910','Geography & travel'),('920','Biography, genealogy & insignia'),('930','History of ancient world'),('940','History of Europe'),('950','History of Asia'),('960','History of Africa'),('970','History of North America'),('980','History of South America'),('990','History of other areas')
on conflict (division_number) do nothing;

create table if not exists public.ddc_sections(id bigint generated by default as identity primary key,section_number text not null unique,division_number text not null,caption text,status text not null default 'Needs licensed/source caption',created_at timestamptz not null default now());
create index if not exists idx_ddc_sections_division on public.ddc_sections(division_number);
insert into public.ddc_sections(section_number,division_number) select lpad(n::text,3,'0'),lpad(((n/10)*10)::text,3,'0') from generate_series(0,999) as g(n) on conflict(section_number) do nothing;

create table if not exists public.app_settings(key text primary key,value text not null default '',updated_at timestamptz not null default now());
insert into public.app_settings(key,value) values('application_name','Accession Register'),('library_name','Sub Divisional Library, Miao'),('backup_enabled','true'),('backup_retention','10') on conflict(key) do nothing;

create table if not exists public.audit_log(id bigint generated by default as identity primary key,table_name text not null,record_id text,action text not null,changed_by text,old_data jsonb,new_data jsonb,created_at timestamptz not null default now());
create index if not exists idx_audit_table_record on public.audit_log(table_name,record_id,created_at desc);
create or replace function public.audit_accession_changes() returns trigger language plpgsql security definer as $$ begin if tg_op='INSERT' then insert into public.audit_log(table_name,record_id,action,new_data) values(tg_table_name,new.id::text,'INSERT',to_jsonb(new)); return new; elsif tg_op='UPDATE' then insert into public.audit_log(table_name,record_id,action,old_data,new_data) values(tg_table_name,new.id::text,'UPDATE',to_jsonb(old),to_jsonb(new)); return new; elsif tg_op='DELETE' then insert into public.audit_log(table_name,record_id,action,old_data) values(tg_table_name,old.id::text,'DELETE',to_jsonb(old)); return old; end if; return null; end; $$;
drop trigger if exists trg_accessions_audit on public.accessions;
create trigger trg_accessions_audit after insert or update or delete on public.accessions for each row execute function public.audit_accession_changes();

alter table public.ddc_divisions enable row level security;
alter table public.ddc_sections enable row level security;
alter table public.app_settings enable row level security;
alter table public.audit_log enable row level security;
drop policy if exists "OPAC can read ddc divisions" on public.ddc_divisions;
create policy "OPAC can read ddc divisions" on public.ddc_divisions for select to anon,authenticated using(true);
drop policy if exists "OPAC can read ddc sections" on public.ddc_sections;
create policy "OPAC can read ddc sections" on public.ddc_sections for select to anon,authenticated using(true);
