-- Overall Accession Register application foundation.
-- Adds hierarchical locations, DDC structure, settings, audit trail and reporting indexes.

alter table public.location_master add column if not exists section_name text;
alter table public.location_master add column if not exists rack_name text;
create index if not exists idx_location_section_rack_shelf on public.location_master(section_name,rack_name,shelf);

alter table public.ddc_master add column if not exists division_number text;
alter table public.ddc_master add column if not exists section_number text;
create index if not exists idx_ddc_division on public.ddc_master(division_number);
create index if not exists idx_ddc_section on public.ddc_master(section_number);

create table if not exists public.ddc_divisions (
  id bigint generated by default as identity primary key,
  division_number text not null unique,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.ddc_sections (
  id bigint generated by default as identity primary key,
  section_number text not null unique,
  division_number text not null,
  caption text,
  status text not null default 'Needs licensed/source caption',
  created_at timestamptz not null default now()
);
create index if not exists idx_ddc_sections_division on public.ddc_sections(division_number);

-- Create the complete numeric 000-999 section framework without reproducing copyrighted captions.
insert into public.ddc_sections(section_number,division_number)
select lpad(n::text,3,'0'), lpad(((n/10)*10)::text,3,'0')
from generate_series(0,999) as g(n)
on conflict (section_number) do nothing;

create table if not exists public.app_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);
insert into public.app_settings(key,value) values
 ('application_name','Accession Register'),
 ('library_name','Sub Divisional Library, Miao'),
 ('backup_enabled','true'),
 ('backup_retention','10')
on conflict (key) do nothing;

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text,
  action text not null,
  changed_by text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_audit_table_record on public.audit_log(table_name,record_id,created_at desc);

create or replace function public.audit_accession_changes() returns trigger
language plpgsql security definer as $$
begin
  if tg_op='INSERT' then
    insert into public.audit_log(table_name,record_id,action,new_data) values (tg_table_name,new.id::text,'INSERT',to_jsonb(new));
    return new;
  elsif tg_op='UPDATE' then
    insert into public.audit_log(table_name,record_id,action,old_data,new_data) values (tg_table_name,new.id::text,'UPDATE',to_jsonb(old),to_jsonb(new));
    return new;
  elsif tg_op='DELETE' then
    insert into public.audit_log(table_name,record_id,action,old_data) values (tg_table_name,old.id::text,'DELETE',to_jsonb(old));
    return old;
  end if;
  return null;
end; $$;

drop trigger if exists trg_accessions_audit on public.accessions;
create trigger trg_accessions_audit after insert or update or delete on public.accessions for each row execute function public.audit_accession_changes();

alter table public.ddc_divisions enable row level security;
alter table public.ddc_sections enable row level security;
alter table public.app_settings enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists "OPAC can read ddc divisions" on public.ddc_divisions;
create policy "OPAC can read ddc divisions" on public.ddc_divisions for select to anon,authenticated using (true);
drop policy if exists "OPAC can read ddc sections" on public.ddc_sections;
create policy "OPAC can read ddc sections" on public.ddc_sections for select to anon,authenticated using (true);
