-- DDC auxiliary master structures. Populate captions/notations from the library's licensed or supplied DDC dataset.
create table if not exists public.ddc_table_entries (
  id bigint generated by default as identity primary key,
  table_code text not null check (table_code in ('T2','T4','T6')),
  notation text not null,
  caption text not null,
  parent_notation text,
  notes text,
  unique(table_code,notation)
);
create index if not exists idx_ddc_table_entries_code_notation on public.ddc_table_entries(table_code,notation);

create table if not exists public.ddc_relative_index (
  id bigint generated by default as identity primary key,
  term text not null,
  ddc_number text not null,
  see_reference text,
  see_also text,
  notes text,
  unique(term,ddc_number)
);
create index if not exists idx_ddc_relative_index_term on public.ddc_relative_index using gin(to_tsvector('simple',term));

alter table public.ddc_table_entries enable row level security;
alter table public.ddc_relative_index enable row level security;
drop policy if exists "OPAC can read ddc tables" on public.ddc_table_entries;
create policy "OPAC can read ddc tables" on public.ddc_table_entries for select to anon,authenticated using(true);
drop policy if exists "OPAC can read ddc relative index" on public.ddc_relative_index;
create policy "OPAC can read ddc relative index" on public.ddc_relative_index for select to anon,authenticated using(true);
