-- 007: Master data system for DDC, Subject, Author, Contributor, Location, Source and RRRLF Scheme.
-- Keeps controlled master data separate from accession transactions.

-- -------------------------
-- SUBJECT MASTER
-- -------------------------
create table if not exists public.subject_master (
  id bigint generated by default as identity primary key,
  subject_name text not null,
  normalized_name text generated always as (lower(regexp_replace(trim(subject_name), '\\s+', ' ', 'g'))) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint subject_master_name_not_blank check (length(trim(subject_name)) > 0),
  constraint uq_subject_master_normalized unique (normalized_name)
);

-- -------------------------
-- AUTHOR MASTER + ALIASES
-- -------------------------
create table if not exists public.author_master (
  id bigint generated by default as identity primary key,
  preferred_name text not null,
  normalized_name text generated always as (lower(regexp_replace(trim(preferred_name), '\\s+', ' ', 'g'))) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint author_master_name_not_blank check (length(trim(preferred_name)) > 0),
  constraint uq_author_master_normalized unique (normalized_name)
);

create table if not exists public.author_aliases (
  id bigint generated by default as identity primary key,
  author_id bigint not null references public.author_master(id) on delete cascade,
  alias_name text not null,
  normalized_alias text generated always as (lower(regexp_replace(trim(alias_name), '\\s+', ' ', 'g'))) stored,
  created_at timestamptz not null default now(),
  constraint author_alias_not_blank check (length(trim(alias_name)) > 0),
  constraint uq_author_alias_normalized unique (normalized_alias)
);

-- -------------------------
-- CONTRIBUTOR MASTER
-- -------------------------
create table if not exists public.contributor_master (
  id bigint generated by default as identity primary key,
  contributor_name text not null,
  normalized_name text generated always as (lower(regexp_replace(trim(contributor_name), '\\s+', ' ', 'g'))) stored,
  contributor_role text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contributor_name_not_blank check (length(trim(contributor_name)) > 0),
  constraint uq_contributor_normalized_role unique (normalized_name, contributor_role)
);

-- Controlled contributor roles. A null role is permitted for 'Other contributor'.
create table if not exists public.contributor_role_master (
  role_name text primary key
);
insert into public.contributor_role_master(role_name) values
  ('Editor'), ('Translator'), ('Compiler'), ('Illustrator'), ('Preface contributor'), ('Other contributor')
on conflict (role_name) do nothing;

-- -------------------------
-- LOCATION MASTER
-- -------------------------
create table if not exists public.location_section_master (
  id bigint generated by default as identity primary key,
  section_name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.location_rack_master (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.location_section_master(id) on delete restrict,
  rack_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(section_id, rack_name)
);

create table if not exists public.location_shelf_master (
  id bigint generated by default as identity primary key,
  rack_id bigint not null references public.location_rack_master(id) on delete restrict,
  shelf_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(rack_id, shelf_name)
);

-- -------------------------
-- CONTROLLED SOURCE / RRRLF SCHEME
-- -------------------------
create table if not exists public.source_master (
  source_name text primary key
);
insert into public.source_master(source_name) values
  ('State Central Library'), ('RRRLF'), ('Donation/Gift')
on conflict (source_name) do nothing;

create table if not exists public.rrrlf_scheme_master (
  scheme_name text primary key
);
insert into public.rrrlf_scheme_master(scheme_name) values
  ('Donated/Gifted by RRRLF'),
  ('Purchased with Assistance from RRRLF'),
  ('Matching Scheme')
on conflict (scheme_name) do nothing;

-- Enforce that only the three approved sources and three approved schemes exist.
create or replace function public.validate_accession_source_scheme()
returns trigger language plpgsql as $$
begin
  if new.source is not null and not exists (select 1 from public.source_master where source_name = new.source) then
    raise exception 'Invalid Source. Use only State Central Library, RRRLF, or Donation/Gift.' using errcode = 'check_violation';
  end if;
  if new.source = 'RRRLF' then
    if new.rrrlf_scheme is null or not exists (select 1 from public.rrrlf_scheme_master where scheme_name = new.rrrlf_scheme) then
      raise exception 'RRRLF Scheme is required and must be one of the three approved schemes.' using errcode = 'check_violation';
    end if;
  elsif new.rrrlf_scheme is not null then
    raise exception 'RRRLF Scheme must be NULL when Source is not RRRLF.' using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_accessions_source_scheme on public.accessions;
create trigger trg_accessions_source_scheme
before insert or update of source, rrrlf_scheme on public.accessions
for each row execute function public.validate_accession_source_scheme();

-- -------------------------
-- DDC SEARCH
-- -------------------------
create or replace function public.search_ddc_master(search_ddc text default null, search_subject text default null)
returns table(id bigint, ddc_number text, subject text)
language sql stable as $$
  select d.id, d.ddc_number, d.subject
  from public.ddc_master d
  where (nullif(trim(search_ddc), '') is null or d.ddc_number ilike '%' || trim(search_ddc) || '%')
    and (nullif(trim(search_subject), '') is null or d.subject ilike '%' || trim(search_subject) || '%')
  order by d.ddc_number;
$$;

-- DDC exact match -> standardized Subject Master when available.
create or replace function public.resolve_ddc_subject(p_ddc text)
returns text language sql stable as $$
  select coalesce(
    (select s.subject_name from public.subject_master s where s.normalized_name = lower(regexp_replace(trim(d.subject), '\\s+', ' ', 'g')) limit 1),
    d.subject
  )
  from public.ddc_master d
  where lower(trim(d.ddc_number)) = lower(trim(p_ddc))
  limit 1;
$$;

-- Subject population remains controlled by DDC Master; Subject Master provides normalization.
create or replace function public.populate_accession_subject_from_ddc()
returns trigger language plpgsql as $$
declare mapped_subject text;
begin
  if nullif(trim(new.ddc_number), '') is not null then
    mapped_subject := public.resolve_ddc_subject(new.ddc_number);
    if mapped_subject is not null and trim(mapped_subject) <> '' then
      new.subject := mapped_subject;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_accessions_ddc_subject on public.accessions;
create trigger trg_accessions_ddc_subject
before insert or update of ddc_number on public.accessions
for each row execute function public.populate_accession_subject_from_ddc();

-- -------------------------
-- LOCATION SAFETY / CONTROLLED REASSIGNMENT
-- -------------------------
create or replace function public.location_usage_count(p_location_id bigint)
returns bigint language sql stable as $$
  select count(*) from public.accessions where location_id = p_location_id;
$$;

create or replace function public.reassign_accessions_location(p_from_location_id bigint, p_to_location_id bigint)
returns bigint language plpgsql as $$
declare moved_count bigint;
begin
  if p_from_location_id = p_to_location_id then
    raise exception 'Source and destination locations must be different.';
  end if;
  if not exists (select 1 from public.location_shelf_master where id = p_to_location_id and active) then
    raise exception 'Destination shelf is not active or does not exist.';
  end if;
  update public.accessions set location_id = p_to_location_id, updated_at = now() where location_id = p_from_location_id;
  get diagnostics moved_count = row_count;
  return moved_count;
end;
$$;

-- Prevent deleting a shelf that is still referenced by accessions.
create or replace function public.prevent_used_shelf_delete()
returns trigger language plpgsql as $$
declare n bigint;
begin
  select count(*) into n from public.accessions where location_id = old.id;
  if n > 0 then
    raise exception 'Cannot delete: % accession records currently use this location.', n using errcode = 'foreign_key_violation';
  end if;
  return old;
end;
$$;

drop trigger if exists trg_prevent_used_shelf_delete on public.location_shelf_master;
create trigger trg_prevent_used_shelf_delete before delete on public.location_shelf_master
for each row execute function public.prevent_used_shelf_delete();

-- RLS for public read-only master data. Writes remain server-side/authorized.
alter table public.subject_master enable row level security;
alter table public.author_master enable row level security;
alter table public.author_aliases enable row level security;
alter table public.contributor_master enable row level security;
alter table public.contributor_role_master enable row level security;
alter table public.location_section_master enable row level security;
alter table public.location_rack_master enable row level security;
alter table public.location_shelf_master enable row level security;
alter table public.source_master enable row level security;
alter table public.rrrlf_scheme_master enable row level security;

-- Read policies for OPAC/forms.
create policy "Read subject master" on public.subject_master for select to anon, authenticated using (true);
create policy "Read author master" on public.author_master for select to anon, authenticated using (true);
create policy "Read author aliases" on public.author_aliases for select to anon, authenticated using (true);
create policy "Read contributor master" on public.contributor_master for select to anon, authenticated using (true);
create policy "Read contributor roles" on public.contributor_role_master for select to anon, authenticated using (true);
create policy "Read location sections" on public.location_section_master for select to anon, authenticated using (true);
create policy "Read location racks" on public.location_rack_master for select to anon, authenticated using (true);
create policy "Read location shelves" on public.location_shelf_master for select to anon, authenticated using (true);
create policy "Read sources" on public.source_master for select to anon, authenticated using (true);
create policy "Read RRRLF schemes" on public.rrrlf_scheme_master for select to anon, authenticated using (true);
